version: ‘2’

services:
    # #PHP
    # php-fpm:
    #     build: ./php-fpm
    #     container_name: php-fpm_docker_sample
    #     working_dir: /application
    #     volumes:
    #         - ./html/myapp/web_app/public_html:/app
    #         - ./php-fpm/php-ini-overrides.ini:/etc/php.d/php-ini-overrides.ini
    
    # PHP Apache
    php-apache:
          build: ./php7.2
          ports:
            - "8080:80"
          volumes:
            - ./html/myapp:/var/www/html
          restart: always
          depends_on:
            - mysql
            # - php-fpm

    # MySQL
    mysql:
      build: ./mysql
      dockerfile: dockerfile
      # ports:
      #   - 3306:3306
      volumes:
        - ./mysql/initdb.d:/docker-entrypoint-initdb.d
        - ./db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'password'
    

  # phpMyAdmin
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_HOSTS: mysql
      restart: always
      ports:
        - 8085:80
      depends_on:
            - mysql

    #MailHog
    mailhog:
        image: mailhog/mailhog
        ports:
            - “8025:8025”
            - “1025:1025”
        environment:
          MH_STORAGE: maildir
          MH_MAILDIR_PATH: /tmp
        volumes:
            - “./mailhog:/tmp”

